// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package welcome

// Injectors from wire.go:

func Wire() *Handler {
	handler := ProvideHandler()
	return handler
}
